# Generated by Django 4.2.1 on 2023-06-11 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminatorWeather', '0003_alter_abnormal_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short', models.CharField(max_length=20, unique=True, verbose_name='English')),
                ('long', models.CharField(max_length=100, verbose_name='Russian')),
                ('page', models.ImageField(upload_to='')),
            ],
            options={
                'db_table': 'advertisement',
                'managed': True,
            },
        ),
        migrations.AlterField(
            model_name='location',
            name='country',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
