# Generated by Django 4.2.1 on 2023-06-12 15:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminatorWeather', '0004_advertisement_alter_location_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forecast',
            name='atmosphericPressure',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='forecast',
            name='averageTem',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='forecast',
            name='maxTem',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='forecast',
            name='minTem',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='forecast',
            name='precipitation',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='forecast',
            name='windSpeed',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='past',
            name='atmosphericPressure',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
